### ISSUE TITLE
Installation Labs

### ISSUE THREAD

**Issue by diolyn** [diolyn/SEBC#3]

**Comment by mfernest** [comment]
You should have one Issue named Installation Labs that will includes all the install exercises.

**Comment by mfernest** [comment]
`1_preinstall.md` - good
`2_replica_working.md` - good
`3_cm_installed.png` - please replace this with an capture that includes the Management Services

**Comment by diolyn** [comment]
Please have a look now; the cluster is alarming as i'm running MR jobs, which pushes the storage utilization..

**Comment by mfernest** [comment]
My apologies, my instructions weren't clear. Capture the image of CM's home page: this image should show both your cluster **and** your management services are up and running.

**Comment by diolyn** [comment]
done - third time lucky...

**Comment by mfernest** [comment]
`3_cm_installed.png` - all good 🎆
