### ISSUE TITLE
Storage Labs

### ISSUE THREAD

**Issue by diolyn** [diolyn/SEBC#4]

**Comment by diolyn** [comment]
**How to access the cluster:** 
The cluster runs on CenturyLink Cloud. Please RDP to the Windows Jump Server on 205.139.17.97. 
Username: mfernest
Password: please check your email

Once logged in, please use the browser and point it to CM which runs on: 
http://sg1dimicdhnod06.local:7180/cmf/login
User account is set up as per the instructions in the lab.

**Comment by mfernest** [comment]
👍
